# Generated by Django 4.1.1 on 2022-09-23 01:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=15, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=256, verbose_name='Password')),
                ('perfil', models.CharField(max_length=30, verbose_name='perfl')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=30, verbose_name='Apellidos')),
                ('telefono', models.CharField(max_length=30, verbose_name='Telefono')),
                ('Correo', models.EmailField(max_length=50, verbose_name='correo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Signos_Vitales',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('Osimetria', models.CharField(max_length=10, unique=True, verbose_name='Osimetria')),
                ('Frecuencia_Respiratoria', models.CharField(max_length=15, unique=True, verbose_name='Frecuencia_Respiratoria')),
                ('Frecuencia_Cardiaca', models.CharField(max_length=15, unique=True, verbose_name='Frecuencia_Cardiaca')),
                ('Temperatura', models.CharField(max_length=15, unique=True, verbose_name='Temperatura')),
                ('Presion_Arterial', models.CharField(max_length=15, unique=True, verbose_name='Presion_Arterial')),
                ('Glicemias', models.CharField(max_length=15, unique=True, verbose_name='Glicemias')),
                ('Fecha_Registro', models.DateTimeField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signos_vitales', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Salud',
            fields=[
                ('id_salud', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=35, verbose_name='Rol')),
                ('especialidad', models.CharField(max_length=35, verbose_name='Especialidad')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Psalud', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id_paciente', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=80, verbose_name='Direccion')),
                ('ciudad', models.CharField(max_length=35, verbose_name='Ciudad')),
                ('fecha_nacimiento', models.DateField()),
                ('id_Psalud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Psalud', to='hospitalapp.personal_salud')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Historia_Clinica',
            fields=[
                ('id_historia', models.AutoField(primary_key=True, serialize=False)),
                ('Descripcion', models.CharField(max_length=50, unique=True, verbose_name='Descripcion')),
                ('recomendaciones', models.CharField(max_length=20, unique=True, verbose_name='Recomendaciones')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Historia', to='hospitalapp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Familiar',
            fields=[
                ('id_familiar', models.AutoField(primary_key=True, serialize=False)),
                ('parentesco', models.CharField(max_length=35, verbose_name='Parentesco')),
                ('correo', models.EmailField(max_length=120, verbose_name='Correo')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Familiar', to='hospitalapp.paciente')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Familiar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
